# add private Qt headers

INCLUDEPATH += $$[QT_INSTALL_HEADERS]/QtCore/$$QT_VERSION/QtCore/
INCLUDEPATH += $$[QT_INSTALL_HEADERS]/QtQml/
INCLUDEPATH += $$[QT_INSTALL_HEADERS]/QtQml/$$QT_VERSION/QtQml/
INCLUDEPATH += $$[QT_INSTALL_HEADERS]/QtV8/$$QT_VERSION/QtV8/
